blank_issues_enabled: false
contact_links:
  - name: Security issue (private)
    url: https://github.com/AurumCoinOrg/AurumCoin/blob/master/SECURITY.md
    about: Please report security vulnerabilities privately. See SECURITY.md.
  - name: Support / Help
    url: https://github.com/AurumCoinOrg/AurumCoin/blob/master/SUPPORT.md
    about: Get help running/building Aurum or using the node/wallet.
